CREATE TABLE users( 
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   FirstName TEXT NOT NULL,
   LastName TEXT NOT NULL,
   UserName TEXT NOT NULL,
   Password TEXT NOT NULL);

CREATE TABLE house(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   Location TEXT NOT NULL,
   UserID INTEGER NOT NULL,
   NRooms INTEGER NOT NULL,
   FOREIGN KEY(UserID) REFERENCES users(id));

CREATE TABLE rooms(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   RoomName TEXT NOT NULL,
   HouseID INTEGER NOT NULL,
   FOREIGN KEY(HouseID) REFERENCES house(id));

CREATE TABLE doors(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   On_Off BOOLEAN NOT NULL,
   RoomID INTEGER NOT NULL,
   FOREIGN KEY(RoomID) REFERENCES rooms(id));

CREATE TABLE lights(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   On_Off BOOLEAN NOT NULL,
   RoomID INTEGER NOT NULL,
   FOREIGN KEY(RoomID) REFERENCES rooms(id));

CREATE TABLE tempSensor(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   RoomID INTEGER NOT NULL,
   value INTEGER NOT NULL,
   maxValue INTEGER NOT NULL CHECK(maxValue < minValue),
   minValue INTEGER NOT NULL CHECK(minValue > maxValue),
   FOREIGN KEY(RoomID) REFERENCES rooms(id));

